### ISSUE TITLE
Missing dataset and instruction to build dataset

### ISSUE THREAD

**Issue by ajaysinh-x** [IDEA-XL/PRESTO#5]
Hi All!,
I am trying to recreate the results but it seems there are some dataset are missing like Interleaved dataset  ( /uspto_rxn_data_filtered.json ).

where can I get the dataset from ? 

Thanks for the great efforts!
cheers!

**Comment by CiaoHe** [comment]
Hi, you can refer from https://huggingface.co/datasets/OpenMol/USPTO_RXN_Interleaved

**Comment by ajaysinh-x** [comment]
Hi @CiaoHe ,

Thanks for your response, I have successfully accessed the dataset, and able to train the model, however I feel, In stage-2 USPTO-Application  dataset,  chat like structure was missing, (defining prompt and and assigned roles to Language Model), there are dedicated functions and classes to handle Interleaved type of data.

In Stage-2 fine tuning , Name Conversion dataset is converted in chat format (defining prompt and assigned roles to Language Model). Every stage has the same convention,  

Is there any reasoning behind using plain text to fine-tune Model in stage-2 ?, Does without Instruction guided fine tuning perform better compared to instruction based, Interleaved fine-tuning ?

**Comment by CiaoHe** [comment]
> Hi @CiaoHe ,
> 
> Thanks for your response, I have successfully accessed the dataset, and able to train the model, however I feel, In stage-2 USPTO-Application dataset, chat like structure was missing, (defining prompt and and assigned roles to Language Model), there are dedicated functions and classes to handle Interleaved type of data.
> 
> In Stage-2 fine tuning , Name Conversion dataset is converted in chat format (defining prompt and assigned roles to Language Model). Every stage has the same convention,
> 
> Is there any reasoning behind using plain text to fine-tune Model in stage-2 ?, Does without Instruction guided fine tuning perform better compared to instruction based, Interleaved fine-tuning ?

In the original design, we treat stage-2 as the `continue-pretrain` stage, which includes the interleaved format dataset (so normally it will not be converted to a chat-like format. You can refer similar ways in Qwen-VL). After experiments, we included name-conversion tasks in stage-2 to boost performance. Hence, the current version of stage-2 mainly uses the two kinds of datasets (kindly confusion, but the result is quite good, as shown in our paper).
