### ISSUE TITLE
Question about stage1.sh

### ISSUE THREAD

**Issue by YanhaoLi-Cc** [IDEA-XL/PRESTO#8]
Hello, I am very interested in your work and have a question I would like to ask.

Should the path in stage1.sh in the readme be `scripts/pretrain_molecule` instead of `scripts/pretrain_multi_molecule`?

> bash scripts/pretrain_multi_molecule/stage1.sh

Looking forward to your reply.

**Comment by CiaoHe** [comment]
Yeah you're right. Thx for pointing it out.
