### ISSUE TITLE
Request for Access to USPTO_RXN_Interleaved Dataset

### ISSUE THREAD

**Issue by YanhaoLi-Cc** [IDEA-XL/PRESTO#9]
I learned about your dataset, **USPTO_RXN_Interleaved**, hosted on Hugging Face, and I am very interested in obtaining access to it. I would like to use this dataset to reproduce the results of your work and further explore its applications in my research.

I kindly request access to this dataset. I have already submitted a request for access to the dataset on Hugging Face.

Thank you for sharing this valuable resource with the community. I appreciate your effort in making such data available and look forward to hearing from you.

https://huggingface.co/datasets/OpenMol/USPTO_RXN_Interleaved

**Comment by CiaoHe** [comment]
Hi, thx for your interest. We've just granted you access. We're welcome to further discussion if you have any interesting ideas or findings. Have fun with it!

**Comment by YanhaoLi-Cc** [comment]
Dear @CiaoHe,

Thank you so much for granting me access to the USPTO_RXN_Interleaved dataset! I sincerely appreciate your prompt response and your generosity in sharing this valuable resource.

I look forward to exploring the dataset and reproducing the results of your work. If I come across any interesting findings or ideas, I would be delighted to discuss them further with you and your team.

Thank you again for your support!
